### ISSUE TITLE
no assets uploaded to repo

### ISSUE THREAD

**Issue by KevinLee3627** [Anonymousbowtie/Normal_minesweeper#2]
The following error occurs when I try to run minesweeper.py after installing the necessary packages:
```
(minesweeper) PS C:\Users\Kevin's PC\Documents\minesweeper\Normal_minesweeper> python .\minesweeper.py
Traceback (most recent call last):
  File "C:\Users\Kevin's PC\Documents\minesweeper\Normal_minesweeper\minesweeper.py", line 21, in <module>
    icon = PhotoImage(file = 'assets/mine.png')
  File "C:\Python310\lib\tkinter\__init__.py", line 4093, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python310\lib\tkinter\__init__.py", line 4038, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "assets/mine.png": no such file or directory
```
adding the images to source control would probably fix it

**Comment by Anonymousbowtie** [comment]
I see, I may have neglected to upload the assets folder properly. Try again now, I’ve uploaded it.

El may. 29, 2022, a la(s) 4:54 p. m., KevinLee3627 ***@***.***> escribió:

﻿

The following error occurs when I try to run minesweeper.py after installing the necessary packages:

(minesweeper) PS C:\Users\Kevin's PC\Documents\minesweeper\Normal_minesweeper> python .\minesweeper.py
Traceback (most recent call last):
  File "C:\Users\Kevin's PC\Documents\minesweeper\Normal_minesweeper\minesweeper.py", line 21, in <module>
    icon = PhotoImage(file = 'assets/mine.png')
  File "C:\Python310\lib\tkinter\__init__.py", line 4093, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Python310\lib\tkinter\__init__.py", line 4038, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "assets/mine.png": no such file or directory


adding the images to source control would probably fix it
